source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NNLayerBackedLabel_Example', :exclusive => true do
  pod "NNLayerBackedLabel", :path => "../"
end

target 'NNLayerBackedLabel_Tests', :exclusive => true do
  pod "NNLayerBackedLabel", :path => "../"

  
end
